In [1]:
import pandas as pd       
import numpy as np        
import glob               
import os                
import warnings
warnings.filterwarnings('ignore')  

print("Libraries imported successfully!")
print(f"   pandas version : {pd.__version__}")
print(f"   numpy  version : {np.__version__}")

Libraries imported successfully!
   pandas version : 2.3.3
   numpy  version : 2.4.2

In [2]:
csv_files = glob.glob('*.csv')
xls_files = glob.glob('*.xls') + glob.glob('*.xlsx')
all_files  = csv_files + xls_files

print(f"FILES FOUND:")
print(f"   CSV files  : {len(csv_files)}")
print(f"   XLS files  : {len(xls_files)}")
print(f"   Total files: {len(all_files)}")

if len(all_files) == 0:
    print("WARNING: No files found! Make sure your CSV/XLS files are in the same folder as this notebook.")
else:
    print(f"   First 5 files: {all_files[:5]}")

FILES FOUND:
   CSV files  : 99
   XLS files  : 0
   Total files: 99
   First 5 files: ['backpacks.csv', 'bath-robe.csv', 'bath-towels.csv', 'bathroom-accessories.csv', 'bedsheets.csv']

In [3]:
all_dataframes = []    
failed_files   = []    
success_count  = 0

print("Reading all files...")
print("-" * 55)

for file in all_files:
    try:
        # Read CSV files
        if file.endswith('.csv'):
            df_temp = pd.read_csv(file, encoding='latin-1')
        # Read XLS/XLSX files
        else:
            df_temp = pd.read_excel(file)

        # Add a column showing which file this row came from
        # os.path.splitext removes extension: 'backpacks.csv' -> 'backpacks'
        df_temp['source_file'] = os.path.splitext(file)[0]

        all_dataframes.append(df_temp)
        success_count += 1
        print(f"   OK  {file:40} -> {len(df_temp):>4} rows")

    except Exception as e:
        failed_files.append(file)
        print(f"   FAILED  {file} -> {e}")

print("-" * 55)
print(f"Successfully loaded : {success_count} files")
if failed_files:
    print(f"Failed to load     : {len(failed_files)} files -> {failed_files}")

Reading all files...
-------------------------------------------------------
   OK  backpacks.csv                            ->    4 rows
   OK  bath-robe.csv                            ->    1 rows
   OK  bath-towels.csv                          ->    1 rows
   OK  bathroom-accessories.csv                 ->    1 rows
   OK  bedsheets.csv                            ->   11 rows
   OK  belts.csv                                ->    1 rows
   OK  bodysuit.csv                             ->    2 rows
   OK  boots.csv                                ->    2 rows
   OK  boxers.csv                               ->    1 rows
   OK  bra.csv                                  ->   13 rows
   OK  bracelet.csv                             ->    4 rows
   OK  briefs.csv                               ->   12 rows
   OK  camisoles.csv                            ->    2 rows
   OK  candle-holders.csv                       ->    1 rows
   OK  caps.csv                                 ->    2 rows
   OK  casual-shoes.csv                         ->   23 rows
   OK  chair-cover.csv                          ->    1 rows
   OK  cleaned_shopping_dataset.csv             -> 2000 rows
   OK  clothing-set.csv                         ->    2 rows
   OK  clutches.csv                             ->    1 rows
   OK  co-ords.csv                              ->    1 rows
   OK  Combined_dataset.csv                     -> 1000 rows
   OK  curtains-and-sheers.csv                  ->    2 rows
   OK  cutlery.csv                              ->    1 rows
   OK  dinnerware.csv                           ->    1 rows
   OK  dresses.csv                              ->  100 rows
   OK  duffel-bag.csv                           ->    2 rows
   OK  dungarees.csv                            ->    1 rows
   OK  dupatta.csv                              ->   11 rows
   OK  earrings.csv                             ->   34 rows
   OK  ethnic-dresses.csv                       ->   20 rows
   OK  face-moisturisers.csv                    ->    2 rows
   OK  face-wash-and-cleanser.csv               ->    1 rows
   OK  flats.csv                                ->   12 rows
   OK  flip-flops.csv                           ->   15 rows
   OK  floor-mats--dhurries.csv                 ->    5 rows
   OK  formal-shoes.csv                         ->   12 rows
   OK  foundation.csv                           ->    1 rows
   OK  gloves.csv                               ->    1 rows
   OK  hair-accessory.csv                       ->    2 rows
   OK  hair-brush-and-comb.csv                  ->    1 rows
   OK  hair-cream-and-mask.csv                  ->    1 rows
   OK  hair-masks.csv                           ->    1 rows
   OK  handbags.csv                             ->   18 rows
   OK  headphones.csv                           ->    3 rows
   OK  heels.csv                                ->    9 rows
   OK  home-fragrance-set.csv                   ->    1 rows
   OK  innerwear-vests.csv                      ->    2 rows
   OK  jackets.csv                              ->   29 rows
   OK  jeans.csv                                ->   57 rows
   OK  jumpsuit.csv                             ->    1 rows
   OK  kurta-sets.csv                           ->   22 rows
   OK  kurtas.csv                               ->   20 rows
   OK  kurtis.csv                               ->    1 rows
   OK  lipstick.csv                             ->    1 rows
   OK  lounge-pants.csv                         ->    1 rows
   OK  lounge-shorts.csv                        ->    1 rows
   OK  lounge-tshirts.csv                       ->    3 rows
   OK  mangalsutra.csv                          ->    1 rows
   OK  mobile-accessories.csv                   ->    1 rows
   OK  night-suits.csv                          ->    3 rows
   OK  nightdress.csv                           ->    4 rows
   OK  outdoor-masks.csv                        ->    2 rows
   OK  palazzos.csv                             ->   12 rows
   OK  perfume-and-body-mist.csv                ->    1 rows
   OK  pillow-covers.csv                        ->    1 rows
   OK  ring.csv                                 ->    3 rows
   OK  runners.csv                              ->    3 rows
   OK  sandals.csv                              ->    6 rows
   OK  saree-blouse.csv                         ->    2 rows
   OK  sarees.csv                               ->   22 rows
   OK  scarves.csv                              ->    2 rows
   OK  shampoo-and-conditioner.csv              ->    3 rows
   OK  shaving-essentials.csv                   ->    1 rows
   OK  sherwani.csv                             ->    5 rows
   OK  shirts.csv                               ->   97 rows
   OK  shorts.csv                               ->   21 rows
   OK  showpieces.csv                           ->    1 rows
   OK  skirts.csv                               ->    6 rows
   OK  sports-shoes.csv                         ->   51 rows
   OK  sunglasses.csv                           ->    1 rows
   OK  sweaters.csv                             ->   34 rows
   OK  sweatshirts.csv                          ->   20 rows
   OK  swim-tops.csv                            ->    1 rows
   OK  table-covers.csv                         ->    1 rows
   OK  thermal-bottoms.csv                      ->    1 rows
   OK  tights.csv                               ->    1 rows
   OK  tops.csv                                 ->  122 rows
   OK  towel-set.csv                            ->    1 rows
   OK  track-pants.csv                          ->    9 rows
   OK  trolley-bag.csv                          ->    1 rows
   OK  trousers.csv                             ->    6 rows
   OK  trunk.csv                                ->    6 rows
   OK  tshirts.csv                              ->   39 rows
   OK  tunics.csv                               ->    4 rows
   OK  wall-art.csv                             ->    1 rows
   OK  wallets.csv                              ->    7 rows
   OK  watches.csv                              ->   15 rows
   OK  yoga-mats.csv                            ->    1 rows
-------------------------------------------------------
Successfully loaded : 99 files

In [4]:
df = pd.concat(all_dataframes, ignore_index=True, sort=False)

print(f"ALL FILES MERGED SUCCESSFULLY!")
print(f"   Total rows    : {len(df):,}")
print(f"   Total columns : {df.shape[1]}")
print()
print("Preview of merged DataFrame:")
df.head()

ALL FILES MERGED SUCCESSFULLY!
   Total rows    : 4,000
   Total columns : 26

Preview of merged DataFrame:

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,source_file,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995.0,58.0,"""â¹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,backpacks,NaN
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899.0,35.0,"""â¹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,backpacks,NaN
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999.0,65.0,"""â¹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,backpacks,NaN
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675.0,52.0,"""â¹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,backpacks,NaN
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899.0,17.0,"""â¹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,bath-robe,NaN

In [5]:
print("FIRST 5 ROWS:")
print("-" * 60)
df.head()

FIRST 5 ROWS:
------------------------------------------------------------

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,source_file,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995.0,58.0,"""â¹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,backpacks,NaN
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899.0,35.0,"""â¹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,backpacks,NaN
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999.0,65.0,"""â¹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,backpacks,NaN
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675.0,52.0,"""â¹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,backpacks,NaN
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899.0,17.0,"""â¹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,bath-robe,NaN

In [6]:
print("LAST 5 ROWS:")
print("-" * 60)
df.tail()

LAST 5 ROWS:
------------------------------------------------------------

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,source_file,total_amount
3995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890.0,50.0,"""â¹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,watches,NaN
3996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900.0,45.0,"""â¹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,watches,NaN
3997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950.0,50.0,"""â¹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,watches,NaN
3998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295.0,20.0,"""â¹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,Truâââm Râââil,"[{""size"":""Onesize""}]",NaN,Shoâââo. âââ-10âââââââ...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches,watches,NaN
3999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699.0,31.0,"""â¹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats,yoga-mats,NaN

In [7]:
print(f"SHAPE: {df.shape}")
print(f"   Rows    : {df.shape[0]:,}")
print(f"   Columns : {df.shape[1]}")
print("=" * 60)

print("ALL COLUMN NAMES:")
for i, col in enumerate(df.columns, 1):
    print(f"   {i:2}. {col}")
print("=" * 60)

print("DATA TYPES:")
print(df.dtypes)

SHAPE: (4000, 26)
   Rows    : 4,000
   Columns : 26
============================================================
ALL COLUMN NAMES:
    1. product_id
    2. title
    3. product_description
    4. rating
    5. ratings_count
    6. initial_price
    7. discount
    8. final_price
    9. currency
   10. images
   11. delivery_options
   12. product_details
   13. breadcrumbs
   14. product_specifications
   15. amount_of_stars
   16. what_customers_said
   17. seller_name
   18. sizes
   19. videos
   20. seller_information
   21. variations
   22. best_offer
   23. more_offers
   24. category
   25. source_file
   26. total_amount
============================================================
DATA TYPES:
product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price             float64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
source_file                object
total_amount              float64
dtype: object

In [8]:
print("SUMMARY STATISTICS - Numeric Columns:")
print("-" * 60)
df.describe()

SUMMARY STATISTICS - Numeric Columns:
------------------------------------------------------------

,product_id,rating,ratings_count,initial_price,discount,total_amount
count,4.000000e+03,4000.000000,4000.000000,4000.000000,3758.000000,2.000000e+03
mean,1.713437e+07,3.621500,76.691000,2723.241000,53.664715,1.954339e+05
std,3.812335e+06,1.373885,241.023805,2407.793703,17.442201,7.695729e+05
min,5.868460e+05,0.000000,0.000000,249.000000,1.000000,0.000000e+00
25%,1.511501e+07,3.700000,7.000000,1399.000000,45.000000,1.082550e+04
50%,1.820890e+07,4.100000,17.000000,1999.000000,56.000000,3.809750e+04
75%,1.902737e+07,4.300000,58.000000,3299.000000,65.000000,1.288455e+05
max,2.274707e+07,5.000000,4441.000000,22199.000000,88.000000,1.564662e+07

In [9]:
print("SUMMARY STATISTICS - Text Columns:")
print("-" * 60)
df.describe(include='object')

SUMMARY STATISTICS - Text Columns:
------------------------------------------------------------

,title,product_description,final_price,currency,images,delivery_options,product_details,breadcrumbs,product_specifications,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,source_file
count,4000,4000,4000,4000,4000,4000,4000,4000,4000,4000,2854,3398,4000,2438,3398,2876,4000,4000,4000,4000
unique,454,989,932,1,1000,16,998,658,967,808,303,600,672,220,597,23,468,318,97,99
top,Roadster,Women Pink Solid Top,"""Ã¢ÂÂ¹999.00""",INR,http://assets.myntassets.com/assets/images/837...,"[""100% Original Products"",""Pay on delivery mig...","{""description"":""Black and White printed knitte...","[{""name"":""Clothing"",""url"":""https://www.myntra....","[{""specification_name"":""Blouse"",""specification...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Unknown,Unknown,"[{""size"":""Onesize""}]",Unknown,Unknown,Unknown,{},"[{""offer_name"":""10% Instant Discount on IndusI...",tops,cleaned_shopping_dataset
freq,120,12,50,4000,4,2600,8,64,16,456,1146,602,540,1562,602,1124,1224,530,488,2000

In [10]:
print("DATASET INFO:")
print("-" * 60)
df.info()

DATASET INFO:
------------------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              4000 non-null   int64
 1   title                   4000 non-null   object
 2   product_description     4000 non-null   object
 3   rating                  4000 non-null   float64
 4   ratings_count           4000 non-null   int64
 5   initial_price           4000 non-null   float64
 6   discount                3758 non-null   float64
 7   final_price             4000 non-null   object
 8   currency                4000 non-null   object
 9   images                  4000 non-null   object
 10  delivery_options        4000 non-null   object
 11  product_details         4000 non-null   object
 12  breadcrumbs             4000 non-null   object
 13  product_specifications  4000 non-null   object
 14  amount_of_stars         4000 non-null   object
 15  what_customers_said     2854 non-null   object
 16  seller_name             3398 non-null   object
 17  sizes                   4000 non-null   object
 18  videos                  2438 non-null   object
 19  seller_information      3398 non-null   object
 20  variations              2876 non-null   object
 21  best_offer              4000 non-null   object
 22  more_offers             4000 non-null   object
 23  category                4000 non-null   object
 24  source_file             4000 non-null   object
 25  total_amount            2000 non-null   float64
dtypes: float64(4), int64(2), object(20)
memory usage: 812.6+ KB

In [11]:
print("PRODUCTS PER CATEGORY (Top 20):")
print("-" * 60)
category_counts = df['category'].value_counts()
print(category_counts.head(20))
print()
print(f"   Total categories : {df['category'].nunique()}")
print(f"   Total products   : {len(df):,}")

PRODUCTS PER CATEGORY (Top 20):
------------------------------------------------------------
category
tops              488
dresses           400
shirts            388
jeans             228
sports-shoes      204
tshirts           156
earrings          136
sweaters          136
jackets           116
casual-shoes       92
kurta-sets         88
sarees             88
shorts             84
kurtas             80
sweatshirts        80
ethnic-dresses     80
handbags           72
watches            60
flip-flops         60
bra                52
Name: count, dtype: int64

   Total categories : 97
   Total products   : 4,000

In [12]:
missing_counts  = df.isnull().sum()
missing_percent = (df.isnull().sum() / len(df) * 100).round(2)

missing_summary = pd.DataFrame({
    'Missing Count' : missing_counts,
    'Missing %'     : missing_percent
})

missing_summary = missing_summary[missing_summary['Missing Count'] > 0].sort_values(
    'Missing Count', ascending=False
)

print(f"MISSING VALUES REPORT:")
print(f"   Total missing cells  : {df.isnull().sum().sum():,}")
print(f"   Columns with missing : {len(missing_summary)}")
print("-" * 50)
print(missing_summary)

MISSING VALUES REPORT:
   Total missing cells  : 7,278
   Columns with missing : 7
--------------------------------------------------
                     Missing Count  Missing %
total_amount                  2000      50.00
videos                        1562      39.05
what_customers_said           1146      28.65
variations                    1124      28.10
seller_name                    602      15.05
seller_information             602      15.05
discount                       242       6.05

In [13]:
original_rows    = len(df)
original_missing = df.isnull().sum().sum()


df_clean = df.copy()

numeric_cols = df_clean.select_dtypes(include=[np.number]).columns

for col in numeric_cols:
    missing_in_col = df_clean[col].isnull().sum()
    if missing_in_col > 0:
        median_val = df_clean[col].median()
        df_clean[col] = df_clean[col].fillna(median_val)
        print(f"   Numeric '{col}': filled {missing_in_col} missing -> median = {median_val:.2f}")

text_cols = df_clean.select_dtypes(include=['object']).columns

for col in text_cols:
    missing_in_col = df_clean[col].isnull().sum()
    if missing_in_col > 0:
        df_clean[col] = df_clean[col].fillna('Unknown')
        print(f"   Text    '{col}': filled {missing_in_col} missing -> 'Unknown'")

threshold        = int(df_clean.shape[1] * 0.5)
rows_before_drop = len(df_clean)
df_clean         = df_clean.dropna(thresh=threshold)
rows_dropped_missing = rows_before_drop - len(df_clean)

print()
print(f"Missing values handled!")
print(f"   Remaining missing cells : {df_clean.isnull().sum().sum()}")
print(f"   Rows dropped            : {rows_dropped_missing}")

   Numeric 'discount': filled 242 missing -> median = 56.00
   Numeric 'total_amount': filled 2000 missing -> median = 38097.50
   Text    'what_customers_said': filled 1146 missing -> 'Unknown'
   Text    'seller_name': filled 602 missing -> 'Unknown'
   Text    'videos': filled 1562 missing -> 'Unknown'
   Text    'seller_information': filled 602 missing -> 'Unknown'
   Text    'variations': filled 1124 missing -> 'Unknown'

Missing values handled!
   Remaining missing cells : 0
   Rows dropped            : 0

In [14]:
useful_cols = [
    'product_id', 'title', 'category',
    'initial_price', 'discount', 'final_price',
    'rating', 'ratings_count', 'sizes', 'currency'
]


useful_cols = [col for col in useful_cols if col in df_clean.columns]

df_selected = df_clean[useful_cols]

print(f"SELECTED {len(useful_cols)} KEY COLUMNS:")
print(f"   Columns: {useful_cols}")
print("-" * 60)
df_selected.head(10)

SELECTED 10 KEY COLUMNS:
   Columns: ['product_id', 'title', 'category', 'initial_price', 'discount', 'final_price', 'rating', 'ratings_count', 'sizes', 'currency']
------------------------------------------------------------

,product_id,title,category,initial_price,discount,final_price,rating,ratings_count,sizes,currency
0,8376765,Lino Perros,backpacks,3995.0,58.0,"""â¹3,995.00""",3.8,15,"[{""size"":""Onesize""}]",INR
1,9136281,Tommy Hilfiger,backpacks,2899.0,35.0,"""â¹2,899.00""",4.5,67,"[{""size"":""Onesize""}]",INR
2,17633752,Lavie,backpacks,2999.0,65.0,"""â¹2,999.00""",4.4,226,"[{""size"":""S""}]",INR
3,1376949,F Gear,backpacks,1675.0,52.0,"""â¹1,675.00""",4.4,1052,"[{""size"":""Onesize""}]",INR
4,13939916,MYTRIDENT,bath-robe,2899.0,17.0,"""â¹2,899.00""",4.7,12,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",INR
5,19851824,AVI Living,bath-towels,1399.0,65.0,"""â¹1,399.00""",4.0,5,"[{""size"":""Onesize""}]",INR
6,17198778,H&M,bathroom-accessories,1399.0,56.0,"""â¹1,399.00""",4.5,42,"[{""size"":""Onesize""}]",INR
7,18602872,My Room,bedsheets,2999.0,54.0,"""â¹2,999.00""",4.7,10,"[{""size"":""Single""},{""size"":""Double Queen""},{""s...",INR
8,18602850,My Room,bedsheets,2999.0,54.0,"""â¹2,999.00""",4.5,22,"[{""size"":""Super King""}]",INR
9,8961147,Story@home,bedsheets,2199.0,53.0,"""â¹2,199.00""",3.7,7,"[{""size"":""Double King""}]",INR

In [15]:
df_high_rated = df_clean[df_clean['rating'] > 4.0]

print(f"FILTER 1: Products with rating above 4.0")
print(f"   Total products        : {len(df_clean):,}")
print(f"   High rated (above 4.0): {len(df_high_rated):,}")
print(f"   Percentage            : {len(df_high_rated)/len(df_clean)*100:.1f}%")
print("-" * 60)
df_high_rated[['title', 'category', 'rating', 'initial_price']].head(8)

FILTER 1: Products with rating above 4.0
   Total products        : 4,000
   High rated (above 4.0): 2,132
   Percentage            : 53.3%
------------------------------------------------------------

             title              category  rating  initial_price
1   Tommy Hilfiger             backpacks     4.5         2899.0
2            Lavie             backpacks     4.4         2999.0
3           F Gear             backpacks     4.4         1675.0
4        MYTRIDENT             bath-robe     4.7         2899.0
6              H&M  bathroom-accessories     4.5         1399.0
7          My Room             bedsheets     4.7         2999.0
8          My Room             bedsheets     4.5         2999.0
10       MYTRIDENT             bedsheets     4.4         2199.0

In [16]:
df_big_discount = df_clean[df_clean['discount'] > 50]

print(f"FILTER 2: Products with discount above 50%")
print(f"   Products with big discount : {len(df_big_discount):,}")
print("-" * 60)
df_big_discount[['title', 'category', 'initial_price', 'discount']].head(8)

FILTER 2: Products with discount above 50%
   Products with big discount : 2,576
------------------------------------------------------------

         title              category  initial_price  discount
0  Lino Perros             backpacks         3995.0      58.0
2        Lavie             backpacks         2999.0      65.0
3       F Gear             backpacks         1675.0      52.0
5   AVI Living           bath-towels         1399.0      65.0
6          H&M  bathroom-accessories         1399.0      56.0
7      My Room             bedsheets         2999.0      54.0
8      My Room             bedsheets         2999.0      54.0
9   Story@home             bedsheets         2199.0      53.0

In [17]:
top_category = df_clean['category'].value_counts().index[0]

df_category = df_clean[df_clean['category'] == top_category]

print(f"FILTER 3: Products in top category = '{top_category}'")
print(f"   Matching products : {len(df_category):,}")
print("-" * 60)
df_category[['title', 'category', 'rating', 'initial_price']].head(8)

FILTER 3: Products in top category = 'tops'
   Matching products : 488
------------------------------------------------------------

               title category  rating  initial_price
956         Oxolloxo     tops     0.0         2299.0
957          MALHAAR     tops     0.0         3329.0
958  her by invictus     tops     4.2         1398.0
959          MALHAAR     tops     0.0         3329.0
960       KiddoPanti     tops     0.0          799.0
961          MALHAAR     tops     0.0         3329.0
962      HILL STREET     tops     4.5         1699.0
963      Zink London     tops     4.3         1499.0

In [18]:
df_sorted_rating = df_clean.sort_values(by='rating', ascending=False)

print("TOP 10 HIGHEST RATED PRODUCTS:")
print("-" * 60)
df_sorted_rating[['title', 'category', 'rating', 'initial_price', 'discount']].head(10)

TOP 10 HIGHEST RATED PRODUCTS:
------------------------------------------------------------

               title        category  rating  initial_price  discount
22        London Rag           boots     5.0         9599.0      60.0
3840       KAMI KUBI            tops     5.0         1299.0      62.0
3881           MANGO            tops     5.0         2490.0      35.0
3917  Bannos Swagger     track-pants     5.0         1699.0      76.0
3658           ASICS          shorts     5.0         2299.0      50.0
3721            Puma    sports-shoes     5.0         6999.0      20.0
52       Bruchi CLUB          briefs     5.0          888.0      65.0
48             Zoiro          briefs     5.0          499.0      56.0
3239      Rustorange  ethnic-dresses     5.0         3299.0      55.0
3082           GUESS         watches     5.0         8900.0      45.0

In [19]:
df_sorted_price = df_clean.sort_values(by='initial_price', ascending=True)

print("TOP 10 CHEAPEST PRODUCTS:")
print("-" * 60)
df_sorted_price[['title', 'category', 'initial_price', 'discount', 'rating']].head(10)

TOP 10 CHEAPEST PRODUCTS:
------------------------------------------------------------

        title   category  initial_price  discount  rating
2311  FemNmas   earrings          249.0      56.0     4.4
2137     XYXX     briefs          249.0      56.0     4.1
1307  FemNmas   earrings          249.0      56.0     4.4
393   FemNmas   earrings          249.0      56.0     4.4
3225  FemNmas   earrings          249.0      56.0     4.4
51       XYXX     briefs          249.0      56.0     4.1
219      XYXX     briefs          249.0      56.0     4.1
133      XYXX     briefs          249.0      56.0     4.1
222     VStar  camisoles          265.0      56.0     4.8
2140    VStar  camisoles          265.0      56.0     4.8

In [20]:
df_multi_sort = df_clean.sort_values(
    by=['category', 'rating'],       
    ascending=[True, False]         
)

print("SORTED by Category (A to Z) then Rating (High to Low):")
print("-" * 60)
df_multi_sort[['category', 'title', 'rating', 'initial_price']].head(10)

SORTED by Category (A to Z) then Rating (High to Low):
------------------------------------------------------------

       category           title  rating  initial_price
1     backpacks  Tommy Hilfiger     4.5         2899.0
83    backpacks  Tommy Hilfiger     4.5         2899.0
169   backpacks  Tommy Hilfiger     4.5         2899.0
2087  backpacks  Tommy Hilfiger     4.5         2899.0
2     backpacks           Lavie     4.4         2999.0
3     backpacks          F Gear     4.4         1675.0
84    backpacks           Lavie     4.4         2999.0
85    backpacks          F Gear     4.4         1675.0
170   backpacks           Lavie     4.4         2999.0
171   backpacks          F Gear     4.4         1675.0

In [21]:
num_duplicates = df_clean.duplicated().sum()

print(f"DUPLICATE CHECK:")
print(f"   Total rows           : {len(df_clean):,}")
print(f"   Duplicate rows found : {num_duplicates:,}")

if num_duplicates > 0:
    print("\n   Sample duplicate rows:")
    print(df_clean[df_clean.duplicated()][['product_id', 'title', 'category']].head(3))
else:
    print("   No duplicates found - dataset is clean!")

DUPLICATE CHECK:
   Total rows           : 4,000
   Duplicate rows found : 1,000

   Sample duplicate rows:
     product_id           title   category
168     8376765     Lino Perros  backpacks
169     9136281  Tommy Hilfiger  backpacks
170    17633752           Lavie  backpacks

In [22]:
rows_before = len(df_clean)

df_clean = df_clean.drop_duplicates(keep='first')

df_clean = df_clean.reset_index(drop=True)

duplicates_removed = rows_before - len(df_clean)

print(f"Duplicates Removed!")
print(f"   Rows before  : {rows_before:,}")
print(f"   Rows removed : {duplicates_removed:,}")
print(f"   Rows after   : {len(df_clean):,}")

Duplicates Removed!
   Rows before  : 4,000
   Rows removed : 1,000
   Rows after   : 3,000

In [23]:
# Create total_amount = initial_price x ratings_count
df_clean['total_amount'] = df_clean['initial_price'] * df_clean['ratings_count']

print("Created 'total_amount' column!")
print("   Formula : total_amount = initial_price x ratings_count")
print("   Meaning : Estimated total revenue per product")
print()

print("New Column Preview:")
print("-" * 60)
print(
    df_clean[['title', 'category', 'initial_price', 'ratings_count', 'total_amount']]
    .head(10)
    .to_string(index=False)
)

print()
print("total_amount Statistics:")
print(f"   Min    : {df_clean['total_amount'].min():>15,.2f}")
print(f"   Max    : {df_clean['total_amount'].max():>15,.2f}")
print(f"   Mean   : {df_clean['total_amount'].mean():>15,.2f}")
print(f"   Median : {df_clean['total_amount'].median():>15,.2f}")
print(f"   Total  : {df_clean['total_amount'].sum():>15,.2f}")

Created 'total_amount' column!
   Formula : total_amount = initial_price x ratings_count
   Meaning : Estimated total revenue per product

New Column Preview:
------------------------------------------------------------
         title             category  initial_price  ratings_count  total_amount
   Lino Perros            backpacks         3995.0             15       59925.0
Tommy Hilfiger            backpacks         2899.0             67      194233.0
         Lavie            backpacks         2999.0            226      677774.0
        F Gear            backpacks         1675.0           1052     1762100.0
     MYTRIDENT            bath-robe         2899.0             12       34788.0
    AVI Living          bath-towels         1399.0              5        6995.0
           H&M bathroom-accessories         1399.0             42       58758.0
       My Room            bedsheets         2999.0             10       29990.0
       My Room            bedsheets         2999.0             22       65978.0
    Story@home            bedsheets         2199.0              7       15393.0

total_amount Statistics:
   Min    :            0.00
   Max    :   15,646,620.00
   Mean   :      195,433.89
   Median :       38,097.50
   Total  :  586,301,664.00

In [24]:
print("TOP 10 PRODUCTS BY ESTIMATED TOTAL REVENUE:")
print("-" * 60)
top_revenue = df_clean.nlargest(10, 'total_amount')
top_revenue[['title', 'category', 'initial_price', 'ratings_count', 'total_amount']]

TOP 10 PRODUCTS BY ESTIMATED TOTAL REVENUE:
------------------------------------------------------------

             title category  initial_price  ratings_count  total_amount
21         Mactree    boots         9060.0           1727    15646620.0
103        Mactree    boots         9060.0           1727    15646620.0
1107       Mactree    boots         9060.0           1727    15646620.0
199         Athena  dresses         2799.0           3797    10627803.0
1203        Athena  dresses         2799.0           3797    10627803.0
2117        Athena  dresses         2799.0           3797    10627803.0
225      SASSAFRAS  dresses         2199.0           4441     9765759.0
1229     SASSAFRAS  dresses         2199.0           4441     9765759.0
2143     SASSAFRAS  dresses         2199.0           4441     9765759.0
1073  Daniel Klein  watches         6950.0            940     6533000.0

In [25]:
output_filename = 'cleaned_shopping_dataset.csv'

df_clean.to_csv(output_filename, index=False, encoding='utf-8')

file_size_kb = os.path.getsize(output_filename) / 1024

print(f"Cleaned dataset saved successfully!")
print(f"   Filename  : {output_filename}")
print(f"   Location  : {os.path.abspath(output_filename)}")
print(f"   File size : {file_size_kb:.1f} KB")
print(f"   Rows      : {len(df_clean):,}")
print(f"   Columns   : {df_clean.shape[1]}")
print()
print("Preview of saved file (first 3 rows):")
df_clean.head(3)

Cleaned dataset saved successfully!
   Filename  : cleaned_shopping_dataset.csv
   Location  : C:\Users\HP\OneDrive\Desktop\ass1\cleaned_shopping_dataset.csv
   File size : 17410.1 KB
   Rows      : 3,000
   Columns   : 26

Preview of saved file (first 3 rows):

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,source_file,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995.0,58.0,"""â¹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,Unknown,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",Unknown,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,backpacks,59925.0
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899.0,35.0,"""â¹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,Unknown,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Unknown,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,backpacks,194233.0
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999.0,65.0,"""â¹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,Unknown,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Unknown,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,backpacks,677774.0

In [26]:
# Final Summary Report
print("=" * 65)
print("          FINAL ASSIGNMENT SUMMARY REPORT")
print("=" * 65)

lines = [
    "",
    "FILES",
    f"   Input  : {success_count} CSV/XLS files merged into one DataFrame",
    "   Output : cleaned_shopping_dataset.csv",
    "",
    "DATASET SIZE",
    f"   Original rows (after merge) : {original_rows:,}",
    f"   Final rows (after cleaning) : {len(df_clean):,}",
    f"   Total columns               : {df_clean.shape[1]}",
    "",
    "MISSING VALUES",
    f"   Missing cells found   : {original_missing:,}",
    "   Strategy:",
    "     Numeric columns -> filled with median",
    "     Text columns    -> filled with 'Unknown'",
    f"     Rows over 50% empty -> dropped ({rows_dropped_missing} rows)",
    "",
    "DUPLICATES",
    f"   Duplicate rows removed : {duplicates_removed:,}",
    "",
    "NEW COLUMNS CREATED",
    "   total_amount = initial_price x ratings_count",
    "   (Estimated revenue proxy per product)",
    "",
    "CATEGORIES",
    f"   Total categories merged : {df_clean['category'].nunique()}",
]
print("\n".join(lines))

print()
print("KEY INSIGHTS:")
print("-" * 65)
print(f"   Average product rating   : {df_clean['rating'].mean():.2f} out of 5.0")
print(f"   Average initial price    : {df_clean['initial_price'].mean():,.2f}")
print(f"   Average discount         : {df_clean['discount'].mean():.1f}%")
print(f"   Most expensive product   : {df_clean['initial_price'].max():,.2f}")
print(f"   Cheapest product         : {df_clean['initial_price'].min():,.2f}")
print(f"   Highest discount         : {df_clean['discount'].max():.0f}%")
print(f"   Top category (most items): {df_clean['category'].value_counts().index[0]}")
print(f"   Total estimated revenue  : {df_clean['total_amount'].sum():,.2f}")
print()
print("=" * 65)

=================================================================
          FINAL ASSIGNMENT SUMMARY REPORT
=================================================================

FILES
   Input  : 99 CSV/XLS files merged into one DataFrame
   Output : cleaned_shopping_dataset.csv

DATASET SIZE
   Original rows (after merge) : 4,000
   Final rows (after cleaning) : 3,000
   Total columns               : 26

MISSING VALUES
   Missing cells found   : 7,278
   Strategy:
     Numeric columns -> filled with median
     Text columns    -> filled with 'Unknown'
     Rows over 50% empty -> dropped (0 rows)

DUPLICATES
   Duplicate rows removed : 1,000

NEW COLUMNS CREATED
   total_amount = initial_price x ratings_count
   (Estimated revenue proxy per product)

CATEGORIES
   Total categories merged : 97

KEY INSIGHTS:
-----------------------------------------------------------------
   Average product rating   : 3.62 out of 5.0
   Average initial price    : 2,723.24
   Average discount         : 53.8%
   Most expensive product   : 22,199.00
   Cheapest product         : 249.00
   Highest discount         : 88%
   Top category (most items): tops
   Total estimated revenue  : 586,301,664.00

=================================================================